### ISSUE TITLE
Crash in login(scope:origin:viewController:callback) at line 65

### ISSUE THREAD

**Issue by UA-JerOdd** [ReachFive/identity-ios-sdk#24]
Hey,

When I call `public func login(scope: [String], origin: String, viewController: UIViewController?, callback: @escaping Callback<AuthToken, ReachFiveError>)` I have a crash at line 65 `GIDSignIn.sharedInstance().signIn()`

When I take a look at `self.providerConfig.clientId` I can see that the value doesn't contain **.com** as shown below:

![Screenshot 2019-08-08 at 15 06 01](https://user-images.githubusercontent.com/53187765/62705697-325fb980-b9ee-11e9-9e98-a91042fd5b8c.png)

However, in the config, I can see that the google id contains it : 

![Screenshot 2019-08-08 at 15 08 17](https://user-images.githubusercontent.com/53187765/62705828-82d71700-b9ee-11e9-8a0b-092a53636866.png)

Do you have any ideas?

Have a good day!

**Comment by Wadjetz** [comment]
Hi, it's a configuration problem in the reachfive console `.com` must be missing in your clientId

**Comment by UA-JerOdd** [comment]
Hey,

I wasn't aware of that! I just checked the provider for iOS and, indeed, the `.com` was missing.
It works fine now! I am closing the issue.

Thanks a lot for your help!
